### PR TITLE
Adds FragmentBundlerCompat

### LINKED ISSUE #3: Doesn't work with support Fragment
I didn't realize we set this up with `android.app.Fragment` and when I tried to used it didnt work since I'm on the support Fragment haha.
Ideas: 
1. Add another FragmentBuilder for support v4 namespace;
2. Instead of relying on the actual fragment class, create an interface, say `Argumentable` that has the method `setArguments` and have your fragments implement that, even though that's not 100% ideal.

I'm in favor of option 2. Ideas?

### PR DESCRIPTION
**Pull request by felipecsl**
Fixes #3

### CODE REVIEW

**Comment by f2prateek** [comment]
Sweet, LGTM. Could you copy over the tests from FragmentBundler and I can merge this and make a release.

**Comment by felipecsl** [comment]
done

**Comment by arturdryomov** [comment]
It seems like this change conflicts with Google-provided support library.

```
compile - Classpath for compiling the main sources.
+--- com.android.support:appcompat-v7:22.1.0
|    \--- com.android.support:support-v4:22.1.0
|         \--- com.android.support:support-annotations:22.1.0
+--- com.android.support:cardview-v7:22.1.0
+--- com.android.support:support-annotations:22.1.0
+--- com.f2prateek.bundler:bundler:1.1.1
     \--- com.google.android:support-v4:r7
```

As a result there are some sweet `DexException` visits of course.

```
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
    at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
    at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
    at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
    at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
    at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
    at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
    at com.android.dx.command.dexer.Main.run(Main.java:246)
    at com.android.dx.command.dexer.Main.main(Main.java:215)
    at com.android.dx.command.Main.main(Main.java:106)
```

**Comment by felipecsl** [comment]
@ming13 you can fix this by adding this to you gradle file:

```
compile('com.f2prateek.bundler:bundler:1.1.1') {
  exclude 'com.google.android:android:r7'
}
```

**Comment by arturdryomov** [comment]
First, you are wrong.

``` gradle
compile('com.f2prateek.bundler:bundler:1.1.1') {
  exclude 'com.google.android:support-v4:r7'
}
```

Second, everybody should use the same hack to just get the library working. It’s 2015, right? Why to use (very much outdated) Central-hosted artifact when Google provides up-to-date dependency and pretty much everyone using it?

@f2prateek to the rescue!

**Comment by felipecsl** [comment]
First, don't be a dick.
Second, if you can't propose a better way to do it, then don't say anything

**Pull request merged**
